Repository googleapis/nodejs-cloud-rad, pull requests merged in 2023-04, with the labels that each got.

#66 refactor: use local snapshot of @google-cloud/deploy package
  test/fixtures/README.md
  test/fixtures/nodejs-deploy/.repo-metadata.json
  test/fixtures/nodejs-deploy/LICENSE
  test/fixtures/nodejs-deploy/README.md
  test/fixtures/nodejs-deploy/package.json
  test/fixtures/nodejs-deploy/protos/google/cloud/deploy/v1/cloud_deploy.proto
  test/fixtures/nodejs-deploy/protos/protos.d.ts
  test/fixtures/nodejs-deploy/protos/protos.js
  test/fixtures/nodejs-deploy/protos/protos.json
  test/fixtures/nodejs-deploy/src/index.ts
  test/fixtures/nodejs-deploy/src/v1/cloud_deploy_client.ts
  test/fixtures/nodejs-deploy/src/v1/cloud_deploy_client_config.json
  test/fixtures/nodejs-deploy/src/v1/cloud_deploy_proto_list.json
  test/fixtures/nodejs-deploy/src/v1/gapic_metadata.json
  test/fixtures/nodejs-deploy/src/v1/index.ts
  test/fixtures/nodejs-deploy/tsconfig.json
  test/fixtures/nodejs-deploy/webpack.config.js
  test/helpers.mjs
Labels: size: xl

#74 fix: pipe subprocess logs to parent process
  lib/generate-yaml.mjs
  package.json
Labels: size: s

#79 fix: output logs for all execa commands
  lib/generate-yaml.mjs
  lib/util.mjs
  main.mjs
  test/helpers.mjs
Labels: size: m

#83 chore(deps): update glob to v10
  lib/process-yaml.mjs
  package.json
Labels: size: xs
